apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ingress.yaml

images:
  - name: docker.io/kemar1/bluearchive-api
    newTag: v2.5.0

configMapGenerator:
  - name: students-config
    files:
      - students.json=data/students.json

generatorOptions:
  disableNameSuffixHash: false
